import 'package:flutter/material.dart';

class ThemeConst {
  //light theme
  static final ThemeData customLightTheme = ThemeData(
    applyElevationOverlayColor: false,
    brightness: Brightness.light,
    buttonTheme: const ButtonThemeData(
      alignedDropdown: false,
      colorScheme: ColorScheme(
        brightness: Brightness.light,
        error: Color(0xffba1a1a),
        errorContainer: Color(0xffffdad6),
        inversePrimary: Color(0xffffb2be),
        inverseSurface: Color(0xff382e2f),
        onError: Color(0xffffffff),
        onErrorContainer: Color(0xff410002),
        onInverseSurface: Color(0xfffeedee),
        onPrimary: Color(0xffffffff),
        onPrimaryContainer: Color(0xff3b0716),
        onSecondary: Color(0xffffffff),
        onSecondaryContainer: Color(0xff2c1519),
        onSurface: Color(0xff22191a),
        onSurfaceVariant: Color(0xff524345),
        onTertiary: Color(0xffffffff),
        onTertiaryContainer: Color(0xff2b1700),
        outline: Color(0xff847375),
        outlineVariant: Color(0xffd6c2c3),
        primary: Color(0xff8e4957),
        primaryContainer: Color(0xffffd9de),
        scrim: Color(0xff000000),
        secondary: Color(0xff75565b),
        secondaryContainer: Color(0xffffd9de),
        shadow: Color(0xff000000),
        surface: Color(0xfffff8f7),
        surfaceContainerHighest: Color(0xfff0dee0),
        surfaceTint: Color(0xff8e4957),
        tertiary: Color(0xff795831),
        tertiaryContainer: Color(0xffffddba),
      ),
      height: 36,
      layoutBehavior: ButtonBarLayoutBehavior.padded,
      minWidth: 88,
      padding: EdgeInsets.symmetric(horizontal: 16),
      shape: RoundedRectangleBorder(
        borderRadius: BorderRadius.only(
          bottomLeft: Radius.elliptical(2, 2),
          bottomRight: Radius.elliptical(2, 2),
          topLeft: Radius.elliptical(2, 2),
          topRight: Radius.elliptical(2, 2),
        ),
        side: BorderSide(
          color: Color(0xff000000),
          width: 0,
          style: BorderStyle.none,
        ),
      ),
      textTheme: ButtonTextTheme.normal,
    ),
    canvasColor: const Color(0xfffff8f7),
    cardColor: const Color(0xfffff8f7),
    colorScheme: const ColorScheme(
      brightness: Brightness.light,
      error: Color(0xffba1a1a),
      errorContainer: Color(0xffffdad6),
      inversePrimary: Color(0xffffb2be),
      inverseSurface: Color(0xff382e2f),
      onError: Color(0xffffffff),
      onErrorContainer: Color(0xff410002),
      onInverseSurface: Color(0xfffeedee),
      onPrimary: Color(0xffffffff),
      onPrimaryContainer: Color(0xff3b0716),
      onSecondary: Color(0xffffffff),
      onSecondaryContainer: Color(0xff2c1519),
      onSurface: Color(0xff22191a),
      onSurfaceVariant: Color(0xff524345),
      onTertiary: Color(0xffffffff),
      onTertiaryContainer: Color(0xff2b1700),
      outline: Color(0xff847375),
      outlineVariant: Color(0xffd6c2c3),
      primary: Color(0xff8e4957),
      primaryContainer: Color(0xffffd9de),
      scrim: Color(0xff000000),
      secondary: Color(0xff75565b),
      secondaryContainer: Color(0xffffd9de),
      shadow: Color(0xff000000),
      surface: Color(0xfffff8f7),
      surfaceContainerHighest: Color(0xfff0dee0),
      surfaceTint: Color(0xff8e4957),
      tertiary: Color(0xff795831),
      tertiaryContainer: Color(0xffffddba),
    ),
    dialogBackgroundColor: const Color(0xfffff8f7),
    disabledColor: const Color(0x61000000),
    dividerColor: const Color(0x1f22191a),
    focusColor: const Color(0x1f000000),
    highlightColor: const Color(0x66bcbcbc),
    hintColor: const Color(0x99000000),
    hoverColor: const Color(0x0a000000),
    iconTheme: const IconThemeData(color: Color(0xdd000000)),
    indicatorColor: const Color(0xffffffff),
    inputDecorationTheme: const InputDecorationTheme(
      alignLabelWithHint: false,
      filled: false,
      floatingLabelAlignment: FloatingLabelAlignment.start,
      floatingLabelBehavior: FloatingLabelBehavior.auto,
      isCollapsed: false,
      isDense: false,
    ),
    materialTapTargetSize: MaterialTapTargetSize.shrinkWrap,
    platform: TargetPlatform.macOS,
    primaryColor: const Color(0xff8e4957),
    primaryColorDark: const Color(0xff1976d2),
    primaryColorLight: const Color(0xffbbdefb),
    primaryIconTheme: const IconThemeData(color: Color(0xffffffff)),
    primaryTextTheme: const TextTheme(
      bodyLarge: TextStyle(
        color: Color(0xfffff8f7),
        decoration: TextDecoration.none,
        decorationColor: Color(0xfffff8f7),
        fontFamily: '.AppleSystemUIFont',
        fontSize: 16,
        fontWeight: FontWeight.w400,
        inherit: false,
        letterSpacing: 0.5,
        textBaseline: TextBaseline.alphabetic,
      ),
      bodyMedium: TextStyle(
        color: Color(0xfffff8f7),
        decoration: TextDecoration.none,
        decorationColor: Color(0xfffff8f7),
        fontFamily: '.AppleSystemUIFont',
        fontSize: 14,
        fontWeight: FontWeight.w400,
        inherit: false,
        letterSpacing: 0.25,
        textBaseline: TextBaseline.alphabetic,
      ),
      bodySmall: TextStyle(
        color: Color(0xfffff8f7),
        decoration: TextDecoration.none,
        decorationColor: Color(0xfffff8f7),
        fontFamily: '.AppleSystemUIFont',
        fontSize: 12,
        fontWeight: FontWeight.w400,
        inherit: false,
        letterSpacing: 0.4,
        textBaseline: TextBaseline.alphabetic,
      ),
      displayLarge: TextStyle(
        color: Color(0xfffff8f7),
        decoration: TextDecoration.none,
        decorationColor: Color(0xfffff8f7),
        fontFamily: '.AppleSystemUIFont',
        fontSize: 96,
        fontWeight: FontWeight.w300,
        inherit: false,
        letterSpacing: -1.5,
        textBaseline: TextBaseline.alphabetic,
      ),
      displayMedium: TextStyle(
        color: Color(0xfffff8f7),
        decoration: TextDecoration.none,
        decorationColor: Color(0xfffff8f7),
        fontFamily: '.AppleSystemUIFont',
        fontSize: 60,
        fontWeight: FontWeight.w300,
        inherit: false,
        letterSpacing: -0.5,
        textBaseline: TextBaseline.alphabetic,
      ),
      displaySmall: TextStyle(
        color: Color(0xfffff8f7),
        decoration: TextDecoration.none,
        decorationColor: Color(0xfffff8f7),
        fontFamily: '.AppleSystemUIFont',
        fontSize: 48,
        fontWeight: FontWeight.w400,
        inherit: false,
        letterSpacing: 0,
        textBaseline: TextBaseline.alphabetic,
      ),
      headlineLarge: TextStyle(
        color: Color(0xfffff8f7),
        decoration: TextDecoration.none,
        decorationColor: Color(0xfffff8f7),
        fontFamily: '.AppleSystemUIFont',
        fontSize: 40,
        fontWeight: FontWeight.w400,
        inherit: false,
        letterSpacing: 0.25,
        textBaseline: TextBaseline.alphabetic,
      ),
      headlineMedium: TextStyle(
        color: Color(0xfffff8f7),
        decoration: TextDecoration.none,
        decorationColor: Color(0xfffff8f7),
        fontFamily: '.AppleSystemUIFont',
        fontSize: 34,
        fontWeight: FontWeight.w400,
        inherit: false,
        letterSpacing: 0.25,
        textBaseline: TextBaseline.alphabetic,
      ),
      headlineSmall: TextStyle(
        color: Color(0xfffff8f7),
        decoration: TextDecoration.none,
        decorationColor: Color(0xfffff8f7),
        fontFamily: '.AppleSystemUIFont',
        fontSize: 24,
        fontWeight: FontWeight.w400,
        inherit: false,
        letterSpacing: 0,
        textBaseline: TextBaseline.alphabetic,
      ),
      labelLarge: TextStyle(
        color: Color(0xfffff8f7),
        decoration: TextDecoration.none,
        decorationColor: Color(0xfffff8f7),
        fontFamily: '.AppleSystemUIFont',
        fontSize: 14,
        fontWeight: FontWeight.w500,
        inherit: false,
        letterSpacing: 1.25,
        textBaseline: TextBaseline.alphabetic,
      ),
      labelMedium: TextStyle(
        color: Color(0xfffff8f7),
        decoration: TextDecoration.none,
        decorationColor: Color(0xfffff8f7),
        fontFamily: '.AppleSystemUIFont',
        fontSize: 11,
        fontWeight: FontWeight.w500,
        inherit: false,
        letterSpacing: 1.5,
        textBaseline: TextBaseline.alphabetic,
      ),
      labelSmall: TextStyle(
        color: Color(0xfffff8f7),
        decoration: TextDecoration.none,
        decorationColor: Color(0xfffff8f7),
        fontFamily: '.AppleSystemUIFont',
        fontSize: 10,
        fontWeight: FontWeight.w400,
        inherit: false,
        letterSpacing: 1.5,
        textBaseline: TextBaseline.alphabetic,
      ),
      titleLarge: TextStyle(
        color: Color(0xfffff8f7),
        decoration: TextDecoration.none,
        decorationColor: Color(0xfffff8f7),
        fontFamily: '.AppleSystemUIFont',
        fontSize: 22,
        fontWeight: FontWeight.w400,
        inherit: false,
        letterSpacing: 0,
        textBaseline: TextBaseline.alphabetic,
      ),
      titleMedium: TextStyle(
        color: Color(0xfffff8f7),
        decoration: TextDecoration.none,
        decorationColor: Color(0xfffff8f7),
        fontFamily: '.AppleSystemUIFont',
        fontSize: 16,
        fontWeight: FontWeight.w500,
        inherit: false,
        letterSpacing: 0.15,
        textBaseline: TextBaseline.alphabetic,
      ),
      titleSmall: TextStyle(
        color: Color(0xfffff8f7),
        decoration: TextDecoration.none,
        decorationColor: Color(0xfffff8f7),
        fontFamily: '.AppleSystemUIFont',
        fontSize: 14,
        fontWeight: FontWeight.w500,
        inherit: false,
        letterSpacing: 0.1,
        textBaseline: TextBaseline.alphabetic,
      ),
    ),
    scaffoldBackgroundColor: const Color(0xfffff8f7),
    secondaryHeaderColor: const Color(0xffffd9de),
    shadowColor: const Color(0xff000000),
    sliderTheme: const SliderThemeData(
      activeTickMarkColor: Color(0x8a8a8a8a),
      activeTrackColor: Color(0x8a8a8a8a),
      inactiveTickMarkColor: Color(0x8a8a8a8a),
      inactiveTrackColor: Color(0x8a8a8a8a),
      overlayColor: Color(0x1f000000),
      thumbColor: Color(0xff000000),
      trackHeight: 2,
    ),
    splashColor: const Color(0x1f000000),
    splashFactory: InkSplash.splashFactory,
    tabBarTheme: const TabBarTheme(
      indicator: UnderlineTabIndicator(
        borderSide: BorderSide(
          color: Color(0x1f000000),
          width: 2,
        ),
      ),
      labelColor: Color(0xff000000),
      unselectedLabelColor: Color(0xb2000000),
    ),
    textButtonTheme: TextButtonThemeData(
      style: ButtonStyle(
        backgroundColor:
            WidgetStateProperty.all<Color>(const Color(0x00000000)),
        foregroundColor:
            WidgetStateProperty.all<Color>(const Color(0xff000000)),
      ),
    ),
    textSelectionTheme: const TextSelectionThemeData(
      cursorColor: Color(0xff000000),
      selectionColor: Color(0x66000000),
      selectionHandleColor: Color(0xff000000),
    ),
    textTheme: const TextTheme(
      bodyLarge: TextStyle(
        color: Color(0xff000000),
        decoration: TextDecoration.none,
        decorationColor: Color(0xff000000),
        fontFamily: '.AppleSystemUIFont',
        fontSize: 16,
        fontWeight: FontWeight.w400,
        inherit: false,
        letterSpacing: 0.5,
        textBaseline: TextBaseline.alphabetic,
      ),
      bodyMedium: TextStyle(
        color: Color(0xff000000),
        decoration: TextDecoration.none,
        decorationColor: Color(0xff000000),
        fontFamily: '.AppleSystemUIFont',
        fontSize: 14,
        fontWeight: FontWeight.w400,
        inherit: false,
        letterSpacing: 0.25,
        textBaseline: TextBaseline.alphabetic,
      ),
      bodySmall: TextStyle(
        color: Color(0xff000000),
        decoration: TextDecoration.none,
        decorationColor: Color(0xff000000),
        fontFamily: '.AppleSystemUIFont',
        fontSize: 12,
        fontWeight: FontWeight.w400,
        inherit: false,
        letterSpacing: 0.4,
        textBaseline: TextBaseline.alphabetic,
      ),
      displayLarge: TextStyle(
        color: Color(0xff000000),
        decoration: TextDecoration.none,
        decorationColor: Color(0xff000000),
        fontFamily: '.AppleSystemUIFont',
        fontSize: 96,
        fontWeight: FontWeight.w300,
        inherit: false,
        letterSpacing: -1.5,
        textBaseline: TextBaseline.alphabetic,
      ),
      displayMedium: TextStyle(
        color: Color(0xff000000),
        decoration: TextDecoration.none,
        decorationColor: Color(0xff000000),
        fontFamily: '.AppleSystemUIFont',
        fontSize: 60,
        fontWeight: FontWeight.w300,
        inherit: false,
        letterSpacing: -0.5,
        textBaseline: TextBaseline.alphabetic,
      ),
      displaySmall: TextStyle(
        color: Color(0xff000000),
        decoration: TextDecoration.none,
        decorationColor: Color(0xff000000),
        fontFamily: '.AppleSystemUIFont',
        fontSize: 48,
        fontWeight: FontWeight.w400,
        inherit: false,
        letterSpacing: 0,
        textBaseline: TextBaseline.alphabetic,
      ),
      headlineLarge: TextStyle(
        color: Color(0xff000000),
        decoration: TextDecoration.none,
        decorationColor: Color(0xff000000),
        fontFamily: '.AppleSystemUIFont',
        fontSize: 40,
        fontWeight: FontWeight.w400,
        inherit: false,
        letterSpacing: 0.25,
        textBaseline: TextBaseline.alphabetic,
      ),
      headlineMedium: TextStyle(
        color: Color(0xff000000),
        decoration: TextDecoration.none,
        decorationColor: Color(0xff000000),
        fontFamily: '.AppleSystemUIFont',
        fontSize: 34,
        fontWeight: FontWeight.w400,
        inherit: false,
        letterSpacing: 0.25,
        textBaseline: TextBaseline.alphabetic,
      ),
      headlineSmall: TextStyle(
        color: Color(0xff000000),
        decoration: TextDecoration.none,
        decorationColor: Color(0xff000000),
        fontFamily: '.AppleSystemUIFont',
        fontSize: 24,
        fontWeight: FontWeight.w400,
        inherit: false,
        letterSpacing: 0,
        textBaseline: TextBaseline.alphabetic,
      ),
      labelLarge: TextStyle(
        color: Color(0xff000000),
        decoration: TextDecoration.none,
        decorationColor: Color(0xff000000),
        fontFamily: '.AppleSystemUIFont',
        fontSize: 14,
        fontWeight: FontWeight.w500,
        inherit: false,
        letterSpacing: 1.25,
        textBaseline: TextBaseline.alphabetic,
      ),
      labelMedium: TextStyle(
        color: Color(0xff000000),
        decoration: TextDecoration.none,
        decorationColor: Color(0xff000000),
        fontFamily: '.AppleSystemUIFont',
        fontSize: 11,
        fontWeight: FontWeight.w500,
        inherit: false,
        letterSpacing: 1.5,
        textBaseline: TextBaseline.alphabetic,
      ),
      labelSmall: TextStyle(
        color: Color(0xff000000),
        decoration: TextDecoration.none,
        decorationColor: Color(0xff000000),
        fontFamily: '.AppleSystemUIFont',
        fontSize: 10,
        fontWeight: FontWeight.w400,
        inherit: false,
        letterSpacing: 1.5,
        textBaseline: TextBaseline.alphabetic,
      ),
      titleLarge: TextStyle(
        color: Color(0xff000000),
        decoration: TextDecoration.none,
        decorationColor: Color(0xff000000),
        fontFamily: '.AppleSystemUIFont',
        fontSize: 22,
        fontWeight: FontWeight.w400,
        inherit: false,
        letterSpacing: 0,
        textBaseline: TextBaseline.alphabetic,
      ),
      titleMedium: TextStyle(
        color: Color(0xff000000),
        decoration: TextDecoration.none,
        decorationColor: Color(0xff000000),
        fontFamily: '.AppleSystemUIFont',
        fontSize: 16,
        fontWeight: FontWeight.w500,
        inherit: false,
        letterSpacing: 0.15,
        textBaseline: TextBaseline.alphabetic,
      ),
      titleSmall: TextStyle(
        color: Color(0xff000000),
        decoration: TextDecoration.none,
        decorationColor: Color(0xff000000),
        fontFamily: '.AppleSystemUIFont',
        fontSize: 14,
        fontWeight: FontWeight.w500,
        inherit: false,
        letterSpacing: 0.1,
        textBaseline: TextBaseline.alphabetic,
      ),
    ),
    unselectedWidgetColor: const Color(0x8a000000),
    useMaterial3: false,
    visualDensity: VisualDensity.adaptivePlatformDensity,
  );

  //dark theme
  static final ThemeData customDarkTheme = ThemeData(
    applyElevationOverlayColor: true,
    brightness: Brightness.dark,
    buttonTheme: ButtonThemeData(
      alignedDropdown: false,
      colorScheme: const ColorScheme.dark(
        error: Color(0xFFFFB4AB),
        errorContainer: Color(0xFF93000A),
        inversePrimary: Color(0xFF8E4957),
        inverseSurface: Color(0xFFF0DEE0),
        onError: Color(0xFF690005),
        onErrorContainer: Color(0xFFFFDAD6),
        onInverseSurface: Color(0xFF382E2F),
        onPrimary: Color(0xFF561D2A),
        onPrimaryContainer: Color(0xFFFFD9DE),
        onSecondary: Color(0xFF43292D),
        onSecondaryContainer: Color(0xFFFFD9DE),
        onSurface: Color(0xFFF0DEE0),
        onSurfaceVariant: Color(0xFFD6C2C3),
        onTertiary: Color(0xFF452B08),
        onTertiaryContainer: Color(0xFFFFDDBA),
        outline: Color(0xFF9F8C8E),
        outlineVariant: Color(0xFF524345),
        primary: Color(0xFFFFB2BE),
        primaryContainer: Color(0xFF71333F),
        scrim: Color(0xFF000000),
        secondary: Color(0xFFE5BDC2),
        secondaryContainer: Color(0xFF5C3F43),
        shadow: Color(0xFF000000),
        surface: Color(0xFF191112),
        surfaceContainerHighest: Color(0xFF3C3233),
        surfaceTint: Color(0xFFFFB2BE),
        tertiary: Color(0xFFEBBF90),
        tertiaryContainer: Color(0xFF5F411C),
      ),
      height: 36,
      layoutBehavior: ButtonBarLayoutBehavior.padded,
      minWidth: 88,
      padding: const EdgeInsets.symmetric(horizontal: 16),
      shape: RoundedRectangleBorder(
        borderRadius: BorderRadius.circular(2),
        side: const BorderSide(
            color: Color(0xFF000000), style: BorderStyle.none, width: 0),
      ),
      textTheme: ButtonTextTheme.normal,
    ),
    canvasColor: const Color(0xFF191112),
    cardColor: const Color(0xFF191112),
    colorScheme: const ColorScheme.dark(
      error: Color(0xFFFFB4AB),
      errorContainer: Color(0xFF93000A),
      inversePrimary: Color(0xFF8E4957),
      inverseSurface: Color(0xFFF0DEE0),
      onError: Color(0xFF690005),
      onErrorContainer: Color(0xFFFFDAD6),
      onInverseSurface: Color(0xFF382E2F),
      onPrimary: Color(0xFF561D2A),
      onPrimaryContainer: Color(0xFFFFD9DE),
      onSecondary: Color(0xFF43292D),
      onSecondaryContainer: Color(0xFFFFD9DE),
      onSurface: Color(0xFFF0DEE0),
      onSurfaceVariant: Color(0xFFD6C2C3),
      onTertiary: Color(0xFF452B08),
      onTertiaryContainer: Color(0xFFFFDDBA),
      outline: Color(0xFF9F8C8E),
      outlineVariant: Color(0xFF524345),
      primary: Color(0xFFFFB2BE),
      primaryContainer: Color(0xFF71333F),
      scrim: Color(0xFF000000),
      secondary: Color(0xFFE5BDC2),
      secondaryContainer: Color(0xFF5C3F43),
      shadow: Color(0xFF000000),
      surface: Color(0xFF191112),
      surfaceContainerHighest: Color(0xFF3C3233),
      surfaceTint: Color(0xFFFFB2BE),
      tertiary: Color(0xFFEBBF90),
      tertiaryContainer: Color(0xFF5F411C),
    ),
    dialogBackgroundColor: const Color(0xFF191112),
    disabledColor: const Color(0x62FFFFFF),
    dividerColor: const Color(0x1FF0DEE0),
    focusColor: const Color(0x1FFFFFFF),
    highlightColor: const Color(0x40CCCCCC),
    hintColor: const Color(0x99FFFFFF),
    hoverColor: const Color(0x0AFFFFFF),
    iconTheme: const IconThemeData(color: Color(0xFFFFFFFF)),
    indicatorColor: const Color(0xFFF0DEE0),
    inputDecorationTheme: const InputDecorationTheme(
      alignLabelWithHint: false,
      filled: false,
      floatingLabelAlignment: FloatingLabelAlignment.start,
      floatingLabelBehavior: FloatingLabelBehavior.auto,
      isCollapsed: false,
      isDense: false,
    ),
    materialTapTargetSize: MaterialTapTargetSize.shrinkWrap,
    platform: TargetPlatform.macOS,
    primaryColor: const Color(0xFF191112),
    primaryColorDark: const Color(0xFF000000),
    primaryColorLight: const Color(0xFF9E9E9E),
    primaryIconTheme: const IconThemeData(color: Color(0xFFFFFFFF)),
    primaryTextTheme: const TextTheme(
      bodyLarge: TextStyle(
        color: Color(0xFFF0DEE0),
        decoration: TextDecoration.none,
        decorationColor: Color(0xFFF0DEE0),
        fontFamily: '.AppleSystemUIFont',
        fontSize: 16,
        fontWeight: FontWeight.w400,
        inherit: false,
        letterSpacing: 0.5,
        textBaseline: TextBaseline.alphabetic,
      ),
      bodyMedium: TextStyle(
        color: Color(0xFFF0DEE0),
        decoration: TextDecoration.none,
        decorationColor: Color(0xFFF0DEE0),
        fontFamily: '.AppleSystemUIFont',
        fontSize: 14,
        fontWeight: FontWeight.w400,
        inherit: false,
        letterSpacing: 0.25,
        textBaseline: TextBaseline.alphabetic,
      ),
      bodySmall: TextStyle(
        color: Color(0xFFF0DEE0),
        decoration: TextDecoration.none,
        decorationColor: Color(0xFFF0DEE0),
        fontFamily: '.AppleSystemUIFont',
        fontSize: 12,
        fontWeight: FontWeight.w400,
        inherit: false,
        letterSpacing: 0.4,
        textBaseline: TextBaseline.alphabetic,
      ),
      displayLarge: TextStyle(
        color: Color(0xFFF0DEE0),
        decoration: TextDecoration.none,
        decorationColor: Color(0xFFF0DEE0),
        fontFamily: '.AppleSystemUIFont',
        fontSize: 96,
        fontWeight: FontWeight.w300,
        inherit: false,
        letterSpacing: -1.5,
        textBaseline: TextBaseline.alphabetic,
      ),
      displayMedium: TextStyle(
        color: Color(0xFFF0DEE0),
        decoration: TextDecoration.none,
        decorationColor: Color(0xFFF0DEE0),
        fontFamily: '.AppleSystemUIFont',
        fontSize: 60,
        fontWeight: FontWeight.w300,
        inherit: false,
        letterSpacing: -0.5,
        textBaseline: TextBaseline.alphabetic,
      ),
      displaySmall: TextStyle(
        color: Color(0xFFF0DEE0),
        decoration: TextDecoration.none,
        decorationColor: Color(0xFFF0DEE0),
        fontFamily: '.AppleSystemUIFont',
        fontSize: 48,
        fontWeight: FontWeight.w400,
        inherit: false,
        letterSpacing: 0,
        textBaseline: TextBaseline.alphabetic,
      ),
      headlineLarge: TextStyle(
        color: Color(0xFFF0DEE0),
        decoration: TextDecoration.none,
        decorationColor: Color(0xFFF0DEE0),
        fontFamily: '.AppleSystemUIFont',
        fontSize: 40,
        fontWeight: FontWeight.w400,
        inherit: false,
        letterSpacing: 0.25,
        textBaseline: TextBaseline.alphabetic,
      ),
      headlineMedium: TextStyle(
        color: Color(0xFFF0DEE0),
        decoration: TextDecoration.none,
        decorationColor: Color(0xFFF0DEE0),
        fontFamily: '.AppleSystemUIFont',
        fontSize: 34,
        fontWeight: FontWeight.w400,
        inherit: false,
        letterSpacing: 0.25,
        textBaseline: TextBaseline.alphabetic,
      ),
      headlineSmall: TextStyle(
        color: Color(0xFFF0DEE0),
        decoration: TextDecoration.none,
        decorationColor: Color(0xFFF0DEE0),
        fontFamily: '.AppleSystemUIFont',
        fontSize: 24,
        fontWeight: FontWeight.w400,
        inherit: false,
        letterSpacing: 0,
        textBaseline: TextBaseline.alphabetic,
      ),
      labelLarge: TextStyle(
        color: Color(0xFFF0DEE0),
        decoration: TextDecoration.none,
        decorationColor: Color(0xFFF0DEE0),
        fontFamily: '.AppleSystemUIFont',
        fontSize: 14,
        fontWeight: FontWeight.w500,
        inherit: false,
        letterSpacing: 1.25,
        textBaseline: TextBaseline.alphabetic,
      ),
      labelMedium: TextStyle(
        color: Color(0xFFF0DEE0),
        decoration: TextDecoration.none,
        decorationColor: Color(0xFFF0DEE0),
        fontFamily: '.AppleSystemUIFont',
        fontSize: 10,
        fontWeight: FontWeight.w500,
        inherit: false,
        letterSpacing: 1.5,
        textBaseline: TextBaseline.alphabetic,
      ),
      labelSmall: TextStyle(
        color: Color(0xFFF0DEE0),
        decoration: TextDecoration.none,
        decorationColor: Color(0xFFF0DEE0),
        fontFamily: '.AppleSystemUIFont',
        fontSize: 10,
        fontWeight: FontWeight.w400,
        inherit: false,
        letterSpacing: 1.5,
        textBaseline: TextBaseline.alphabetic,
      ),
      titleLarge: TextStyle(
        color: Color(0xFFF0DEE0),
        decoration: TextDecoration.none,
        decorationColor: Color(0xFFF0DEE0),
        fontFamily: '.AppleSystemUIFont',
        fontSize: 20,
        fontWeight: FontWeight.w400,
        inherit: false,
        letterSpacing: 0.15,
        textBaseline: TextBaseline.alphabetic,
      ),
      titleMedium: TextStyle(
        color: Color(0xFFF0DEE0),
        decoration: TextDecoration.none,
        decorationColor: Color(0xFFF0DEE0),
        fontFamily: '.AppleSystemUIFont',
        fontSize: 16,
        fontWeight: FontWeight.w500,
        inherit: false,
        letterSpacing: 0.15,
        textBaseline: TextBaseline.alphabetic,
      ),
      titleSmall: TextStyle(
        color: Color(0xFFF0DEE0),
        decoration: TextDecoration.none,
        decorationColor: Color(0xFFF0DEE0),
        fontFamily: '.AppleSystemUIFont',
        fontSize: 14,
        fontWeight: FontWeight.w500,
        inherit: false,
        letterSpacing: 0.1,
        textBaseline: TextBaseline.alphabetic,
      ),
    ),
    scaffoldBackgroundColor: const Color(0xFF191112),
    splashColor: const Color(0x1FFFFFFF),
    textSelectionTheme: const TextSelectionThemeData(
      cursorColor: Color(0xFFFFFFFF),
      selectionColor: Color(0xFFBE878C),
      selectionHandleColor: Color(0xFFFFB2BE),
    ),
    textTheme: const TextTheme(
      bodyLarge: TextStyle(
        color: Color(0xFFF0DEE0),
        decoration: TextDecoration.none,
        decorationColor: Color(0xFFF0DEE0),
        fontFamily: '.AppleSystemUIFont',
        fontSize: 16,
        fontWeight: FontWeight.w400,
        inherit: false,
        letterSpacing: 0.5,
        textBaseline: TextBaseline.alphabetic,
      ),
      bodyMedium: TextStyle(
        color: Color(0xFFF0DEE0),
        decoration: TextDecoration.none,
        decorationColor: Color(0xFFF0DEE0),
        fontFamily: '.AppleSystemUIFont',
        fontSize: 14,
        fontWeight: FontWeight.w400,
        inherit: false,
        letterSpacing: 0.25,
        textBaseline: TextBaseline.alphabetic,
      ),
      bodySmall: TextStyle(
        color: Color(0xFFF0DEE0),
        decoration: TextDecoration.none,
        decorationColor: Color(0xFFF0DEE0),
        fontFamily: '.AppleSystemUIFont',
        fontSize: 12,
        fontWeight: FontWeight.w400,
        inherit: false,
        letterSpacing: 0.4,
        textBaseline: TextBaseline.alphabetic,
      ),
      displayLarge: TextStyle(
        color: Color(0xFFF0DEE0),
        decoration: TextDecoration.none,
        decorationColor: Color(0xFFF0DEE0),
        fontFamily: '.AppleSystemUIFont',
        fontSize: 96,
        fontWeight: FontWeight.w300,
        inherit: false,
        letterSpacing: -1.5,
        textBaseline: TextBaseline.alphabetic,
      ),
      displayMedium: TextStyle(
        color: Color(0xFFF0DEE0),
        decoration: TextDecoration.none,
        decorationColor: Color(0xFFF0DEE0),
        fontFamily: '.AppleSystemUIFont',
        fontSize: 60,
        fontWeight: FontWeight.w300,
        inherit: false,
        letterSpacing: -0.5,
        textBaseline: TextBaseline.alphabetic,
      ),
      displaySmall: TextStyle(
        color: Color(0xFFF0DEE0),
        decoration: TextDecoration.none,
        decorationColor: Color(0xFFF0DEE0),
        fontFamily: '.AppleSystemUIFont',
        fontSize: 48,
        fontWeight: FontWeight.w400,
        inherit: false,
        letterSpacing: 0,
        textBaseline: TextBaseline.alphabetic,
      ),
      headlineLarge: TextStyle(
        color: Color(0xFFF0DEE0),
        decoration: TextDecoration.none,
        decorationColor: Color(0xFFF0DEE0),
        fontFamily: '.AppleSystemUIFont',
        fontSize: 40,
        fontWeight: FontWeight.w400,
        inherit: false,
        letterSpacing: 0.25,
        textBaseline: TextBaseline.alphabetic,
      ),
      headlineMedium: TextStyle(
        color: Color(0xFFF0DEE0),
        decoration: TextDecoration.none,
        decorationColor: Color(0xFFF0DEE0),
        fontFamily: '.AppleSystemUIFont',
        fontSize: 34,
        fontWeight: FontWeight.w400,
        inherit: false,
        letterSpacing: 0.25,
        textBaseline: TextBaseline.alphabetic,
      ),
      headlineSmall: TextStyle(
        color: Color(0xFFF0DEE0),
        decoration: TextDecoration.none,
        decorationColor: Color(0xFFF0DEE0),
        fontFamily: '.AppleSystemUIFont',
        fontSize: 24,
        fontWeight: FontWeight.w400,
        inherit: false,
        letterSpacing: 0,
        textBaseline: TextBaseline.alphabetic,
      ),
      labelLarge: TextStyle(
        color: Color(0xFFF0DEE0),
        decoration: TextDecoration.none,
        decorationColor: Color(0xFFF0DEE0),
        fontFamily: '.AppleSystemUIFont',
        fontSize: 14,
        fontWeight: FontWeight.w500,
        inherit: false,
        letterSpacing: 1.25,
        textBaseline: TextBaseline.alphabetic,
      ),
      labelMedium: TextStyle(
        color: Color(0xFFF0DEE0),
        decoration: TextDecoration.none,
        decorationColor: Color(0xFFF0DEE0),
        fontFamily: '.AppleSystemUIFont',
        fontSize: 10,
        fontWeight: FontWeight.w500,
        inherit: false,
        letterSpacing: 1.5,
        textBaseline: TextBaseline.alphabetic,
      ),
      labelSmall: TextStyle(
        color: Color(0xFFF0DEE0),
        decoration: TextDecoration.none,
        decorationColor: Color(0xFFF0DEE0),
        fontFamily: '.AppleSystemUIFont',
        fontSize: 10,
        fontWeight: FontWeight.w400,
        inherit: false,
        letterSpacing: 1.5,
        textBaseline: TextBaseline.alphabetic,
      ),
      titleLarge: TextStyle(
        color: Color(0xFFF0DEE0),
        decoration: TextDecoration.none,
        decorationColor: Color(0xFFF0DEE0),
        fontFamily: '.AppleSystemUIFont',
        fontSize: 20,
        fontWeight: FontWeight.w400,
        inherit: false,
        letterSpacing: 0.15,
        textBaseline: TextBaseline.alphabetic,
      ),
      titleMedium: TextStyle(
        color: Color(0xFFF0DEE0),
        decoration: TextDecoration.none,
        decorationColor: Color(0xFFF0DEE0),
        fontFamily: '.AppleSystemUIFont',
        fontSize: 16,
        fontWeight: FontWeight.w500,
        inherit: false,
        letterSpacing: 0.15,
        textBaseline: TextBaseline.alphabetic,
      ),
      titleSmall: TextStyle(
        color: Color(0xFFF0DEE0),
        decoration: TextDecoration.none,
        decorationColor: Color(0xFFF0DEE0),
        fontFamily: '.AppleSystemUIFont',
        fontSize: 14,
        fontWeight: FontWeight.w500,
        inherit: false,
        letterSpacing: 0.1,
        textBaseline: TextBaseline.alphabetic,
      ),
    ),
    unselectedWidgetColor: const Color(0xFFD6C2C3),
    useMaterial3: true,
    visualDensity: VisualDensity.standard,
  );
}
